---
- name: Going to run for app "{{ item }}"
  ansible.builtin.debug:
    msg: Going to run for app "{{ item }}"

- name: Create and start app containers for app "{{ item }}"
  # `docker compose up` has a bug where if this is the first time an image is
  # pulled, running `docker compose up` again will cause the containers to be
  # recreated.
  # See: https://github.com/docker/compose/issues/9600
  tags: molecule-idempotence-notest
  ansible.builtin.command:
    chdir: "{{ docker_directory }}/apps/{{ item }}"
    cmd: >
      {{ docker_compose_command }}
      --file compose.yml
      --project-name {{ item }}
      up
      --detach
      --remove-orphans
  async: 300
  poll: 0
  register: docker_compose_up_result
#  register: docker_compose_up_result
#  changed_when: >
#    'Creating' in docker_compose_up_result.stderr or
#    'Recreating' in docker_compose_up_result.stderr or
#    'Starting' in docker_compose_up_result.stderr or
#    'Stopping' in docker_compose_up_result.stderr

- name: Finished running for app "{{ item }}"
  ansible.builtin.debug:
    msg: Finished running for app "{{ item }}"
